### ISSUE TITLE
请问这个仓库和 apache 的仓库有什么区别呢

### ISSUE THREAD

**Issue by WarsFeng** [vivo/dubbo-js#1]
包括 master 分支, 3.0, 4.0 分支各自的区别能给讲讲嘛感谢.

**Comment by WarsFeng** [comment]
@hufeng

**Comment by hufeng** [comment]
hi @WarsFeng , 该仓库是vivo内部开源协同的dubbo-js的仓库，我们的内部的代码改进都会推送在这个仓库 然后pr到apache上游的仓库

3.0 其实并没有发布 - 当时在将发布的时候 发现了架构上做还不够完善的地方 如tcp长连接的负载均衡等，另外考虑到模块后续会越来越多，在一个模块中维护代码会变得比较挑战，所以我们对模块进行了拆分，各司其职更清晰，也好让小伙伴参与进来

这些改进都和入了4.0中，目前4.0以及放出来 欢迎帮助review下 很快我们就会在apache社区发起投票然后发布新版本

**Comment by WarsFeng** [comment]
@hufeng  好嘞谢谢解答, 看了一下 Nacos 部分的代码有点不完善, 最近项目有 Java <=> Node 的需求, 应该过段时间会贡献点 Nacos 相关的代码.

**Comment by hufeng** [comment]
期待以前改进，目前nacos在master分支优化了下，添加服务监听能力

Wars ***@***.***> 于2021年6月29日周二 上午9:43写道：
