### ISSUE TITLE
[Kernel Sourcecode] Stop Violating GPL Vivo Release Kernel Sources

### ISSUE THREAD

**Issue by techyminati** [vivo/dubbo-js#2]
Hello , The Android kernel Sourcecode are under GNU/GPL licensing that means they should be public at any cost. Still vivo is not making Android kernels public violating GPL license. If you're not incharge of vivo Android department please tell them to release sources asap.

**Comment by techyminati** [comment]
> Hello , The Android kernel Sourcecode are under GNU/GPL licensing that means they should be public at any cost. Still vivo is not making Android kernels public violating GPL license. If you're not incharge of vivo Android department please tell them to release sources asap.

@hufeng

**Comment by hufeng** [comment]
1. Thanks for your attention and suggestions
2. We have open sourced to https://opensource.vivo.com
3. We joined the linux foundation and started to submit patches for the linux kernel

**Comment by techyminati** [comment]
Hello Developer, Thank you for replies . I can't find any Sourcecode there , will be they push it soon? . Thank you !!

**Comment by DavidWithTuxedo** [comment]
> Hello Developer, Thank you for replies . I can't find any Sourcecode there , will be they push it soon? . Thank you !!

Please click the "Mobile" button in the upper right corner, then the kernel source codes will appear.

But in fact, only these devices.
![IMG_20210810_120533](https://user-images.githubusercontent.com/85795570/128812300-785a02d7-e0d6-4257-8185-664c84bd53ba.jpg)
I think that they will not release kernel source of products not sold in Europe and America.

**Comment by techyminati** [comment]
> > Hello Developer, Thank you for replies . I can't find any Sourcecode there , will be they push it soon? . Thank you !!
> 
> Please click the "Mobile" button in the upper right corner, then the kernel source codes will appear.
> 
> But in fact, only these devices.
> ![IMG_20210810_120533](https://user-images.githubusercontent.com/85795570/128812300-785a02d7-e0d6-4257-8185-664c84bd53ba.jpg)
> I think that they will not release kernel source of products not sold in Europe and America.

Okay Thank You

**Comment by techyminati** [comment]
Thank you @hufeng !!

**Comment by DavidWithTuxedo** [comment]
> 1. Thanks for your attention and suggestions
> 2. We have open sourced to https://opensource.vivo.com
> 3. We joined the linux foundation and started to submit patches for the linux kernel

@hufeng 
Dear Engineer, sorry to disturb you in your busy schedule.

Sadly I can't find kernel source of the VIVO Y81S(PD1732) at that website. Would you please tell me where to find it?

Thanks in advance!
