### ISSUE TITLE
[VIVO Y81S(PD1732)] Inquire about Kernel Source

### ISSUE THREAD

**Issue by DavidWithTuxedo** [vivo/dubbo-js#3]
@hufeng 
Dear Engineer, sorry to disturb you in your busy schedule. 

I have tried the link mentioned at #2 , https://opensource.vivo.com/Project .
But it seems that there is no kernel source of VIVO Y81S(PD1732), Would you please tell me where to find it?
![IMG_20210810_143737](https://user-images.githubusercontent.com/85795570/128819870-c65a159b-054b-4ca5-93ec-ae52fc4978e4.jpg)
![IMG_20210810_120533](https://user-images.githubusercontent.com/85795570/128819712-e93fc491-6a25-4a32-954e-a7a996a17014.jpg)

Thanks in advance!

**Comment by NeonzGamingYT** [comment]
I also need kernel release for vivo Y11 2019 (PD1930F/CF)! This phone is so good, why dont release it

**Comment by DavidWithTuxedo** [comment]
Hello! Maybe we users can't do anything about this.
You can see this discussion, never a reply for three months.
https://github.com/vivo/vivo.github.io/issues/1
